-- Setup 
CREATE DATABASE IF NOT EXISTS STOCK_DW;

-- Schema creation 
CREATE SCHEMA IF NOT EXISTS STOCK_DW.RAW;
CREATE SCHEMA IF NOT EXISTS STOCK_DW.STAGING;
CREATE SCHEMA IF NOT EXISTS STOCK_DW.ANALYTICS;

-- SQL warehouse creation 
CREATE WAREHOUSE  IF NOT EXISTS STOCK_WH WITH WAREHOUSE_SIZE = 'XSMALL'